export type OperandKind =
  | "none"
  | "u8"
  | "u30"
  | "s24"
  | "u30_u30"
  | "u30_u8"
  | "s24_s24_s24_u30"
  | "debug";

export interface OpcodeInfo {
  op: number;
  name: string;
  operand: OperandKind;
}

const TABLE: OpcodeInfo[] = [
  { op: 0x01, name: "bkpt", operand: "none" },
  { op: 0x02, name: "nop", operand: "none" },
  { op: 0x03, name: "throw", operand: "none" },
  { op: 0x04, name: "getsuper", operand: "u30" },
  { op: 0x05, name: "setsuper", operand: "u30" },
  { op: 0x06, name: "dxns", operand: "u30" },
  { op: 0x07, name: "dxnslate", operand: "none" },
  { op: 0x08, name: "kill", operand: "u30" },
  { op: 0x09, name: "label", operand: "none" },
  { op: 0x0c, name: "ifnlt", operand: "s24" },
  { op: 0x0d, name: "ifnle", operand: "s24" },
  { op: 0x0e, name: "ifngt", operand: "s24" },
  { op: 0x0f, name: "ifnge", operand: "s24" },
  { op: 0x10, name: "jump", operand: "s24" },
  { op: 0x11, name: "iftrue", operand: "s24" },
  { op: 0x12, name: "iffalse", operand: "s24" },
  { op: 0x13, name: "ifeq", operand: "s24" },
  { op: 0x14, name: "ifne", operand: "s24" },
  { op: 0x15, name: "iflt", operand: "s24" },
  { op: 0x16, name: "ifle", operand: "s24" },
  { op: 0x17, name: "ifgt", operand: "s24" },
  { op: 0x18, name: "ifge", operand: "s24" },
  { op: 0x19, name: "ifstricteq", operand: "s24" },
  { op: 0x1a, name: "ifstrictne", operand: "s24" },
  { op: 0x1b, name: "lookupswitch", operand: "s24_s24_s24_u30" },
  { op: 0x1c, name: "pushwith", operand: "none" },
  { op: 0x1d, name: "popscope", operand: "none" },
  { op: 0x1e, name: "nextname", operand: "none" },
  { op: 0x1f, name: "hasnext", operand: "none" },
  { op: 0x20, name: "pushnull", operand: "none" },
  { op: 0x21, name: "pushundefined", operand: "none" },
  { op: 0x23, name: "nextvalue", operand: "none" },
  { op: 0x24, name: "pushbyte", operand: "u8" },
  { op: 0x25, name: "pushshort", operand: "u30" },
  { op: 0x26, name: "pushtrue", operand: "none" },
  { op: 0x27, name: "pushfalse", operand: "none" },
  { op: 0x28, name: "pushnan", operand: "none" },
  { op: 0x29, name: "pop", operand: "none" },
  { op: 0x2a, name: "dup", operand: "none" },
  { op: 0x2b, name: "swap", operand: "none" },
  { op: 0x2c, name: "pushstring", operand: "u30" },
  { op: 0x2d, name: "pushint", operand: "u30" },
  { op: 0x2e, name: "pushuint", operand: "u30" },
  { op: 0x2f, name: "pushdouble", operand: "u30" },
  { op: 0x30, name: "pushscope", operand: "none" },
  { op: 0x31, name: "pushnamespace", operand: "u30" },
  { op: 0x32, name: "hasnext2", operand: "u30_u30" },
  { op: 0x35, name: "li8", operand: "none" },
  { op: 0x36, name: "li16", operand: "none" },
  { op: 0x37, name: "li32", operand: "none" },
  { op: 0x38, name: "lf32", operand: "none" },
  { op: 0x39, name: "lf64", operand: "none" },
  { op: 0x3a, name: "si8", operand: "none" },
  { op: 0x3b, name: "si16", operand: "none" },
  { op: 0x3c, name: "si32", operand: "none" },
  { op: 0x3d, name: "sf32", operand: "none" },
  { op: 0x3e, name: "sf64", operand: "none" },
  { op: 0x40, name: "newfunction", operand: "u30" },
  { op: 0x41, name: "call", operand: "u30" },
  { op: 0x42, name: "construct", operand: "u30" },
  { op: 0x43, name: "callmethod", operand: "u30_u30" },
  { op: 0x44, name: "callstatic", operand: "u30_u30" },
  { op: 0x45, name: "callsuper", operand: "u30_u30" },
  { op: 0x46, name: "callproperty", operand: "u30_u30" },
  { op: 0x47, name: "returnvoid", operand: "none" },
  { op: 0x48, name: "returnvalue", operand: "none" },
  { op: 0x49, name: "constructsuper", operand: "u30" },
  { op: 0x4a, name: "constructprop", operand: "u30_u30" },
  { op: 0x4c, name: "callproplex", operand: "u30_u30" },
  { op: 0x4e, name: "callsupervoid", operand: "u30_u30" },
  { op: 0x4f, name: "callpropvoid", operand: "u30_u30" },
  { op: 0x50, name: "sxi1", operand: "none" },
  { op: 0x51, name: "sxi8", operand: "none" },
  { op: 0x52, name: "sxi16", operand: "none" },
  { op: 0x53, name: "applytype", operand: "u30" },
  { op: 0x55, name: "newobject", operand: "u30" },
  { op: 0x56, name: "newarray", operand: "u30" },
  { op: 0x57, name: "newactivation", operand: "none" },
  { op: 0x58, name: "newclass", operand: "u30" },
  { op: 0x59, name: "getdescendants", operand: "u30" },
  { op: 0x5a, name: "newcatch", operand: "u30" },
  { op: 0x5d, name: "findpropstrict", operand: "u30" },
  { op: 0x5e, name: "findproperty", operand: "u30" },
  { op: 0x5f, name: "finddef", operand: "u30" },
  { op: 0x60, name: "getlex", operand: "u30" },
  { op: 0x61, name: "setproperty", operand: "u30" },
  { op: 0x62, name: "getlocal", operand: "u30" },
  { op: 0x63, name: "setlocal", operand: "u30" },
  { op: 0x64, name: "getglobalscope", operand: "none" },
  { op: 0x65, name: "getscopeobject", operand: "u8" },
  { op: 0x66, name: "getproperty", operand: "u30" },
  { op: 0x68, name: "initproperty", operand: "u30" },
  { op: 0x6a, name: "deleteproperty", operand: "u30" },
  { op: 0x6c, name: "getslot", operand: "u30" },
  { op: 0x6d, name: "setslot", operand: "u30" },
  { op: 0x6e, name: "getglobalslot", operand: "u30" },
  { op: 0x6f, name: "setglobalslot", operand: "u30" },
  { op: 0x70, name: "convert_s", operand: "none" },
  { op: 0x71, name: "esc_xelem", operand: "none" },
  { op: 0x72, name: "esc_xattr", operand: "none" },
  { op: 0x73, name: "convert_i", operand: "none" },
  { op: 0x74, name: "convert_u", operand: "none" },
  { op: 0x75, name: "convert_d", operand: "none" },
  { op: 0x76, name: "convert_b", operand: "none" },
  { op: 0x77, name: "convert_o", operand: "none" },
  { op: 0x78, name: "checkfilter", operand: "none" },
  { op: 0x80, name: "coerce", operand: "u30" },
  { op: 0x81, name: "coerce_b", operand: "none" },
  { op: 0x82, name: "coerce_a", operand: "none" },
  { op: 0x83, name: "coerce_i", operand: "none" },
  { op: 0x84, name: "coerce_d", operand: "none" },
  { op: 0x85, name: "coerce_s", operand: "none" },
  { op: 0x86, name: "astype", operand: "u30" },
  { op: 0x87, name: "astypelate", operand: "none" },
  { op: 0x88, name: "coerce_u", operand: "none" },
  { op: 0x89, name: "coerce_o", operand: "none" },
  { op: 0x90, name: "negate", operand: "none" },
  { op: 0x91, name: "increment", operand: "none" },
  { op: 0x92, name: "inclocal", operand: "u30" },
  { op: 0x93, name: "decrement", operand: "none" },
  { op: 0x94, name: "declocal", operand: "u30" },
  { op: 0x95, name: "typeof", operand: "none" },
  { op: 0x96, name: "not", operand: "none" },
  { op: 0x97, name: "bitnot", operand: "none" },
  { op: 0xa0, name: "add", operand: "none" },
  { op: 0xa1, name: "subtract", operand: "none" },
  { op: 0xa2, name: "multiply", operand: "none" },
  { op: 0xa3, name: "divide", operand: "none" },
  { op: 0xa4, name: "modulo", operand: "none" },
  { op: 0xa5, name: "lshift", operand: "none" },
  { op: 0xa6, name: "rshift", operand: "none" },
  { op: 0xa7, name: "urshift", operand: "none" },
  { op: 0xa8, name: "bitand", operand: "none" },
  { op: 0xa9, name: "bitor", operand: "none" },
  { op: 0xaa, name: "bitxor", operand: "none" },
  { op: 0xab, name: "equals", operand: "none" },
  { op: 0xac, name: "strictequals", operand: "none" },
  { op: 0xad, name: "lessthan", operand: "none" },
  { op: 0xae, name: "lessequals", operand: "none" },
  { op: 0xaf, name: "greaterthan", operand: "none" },
  { op: 0xb0, name: "greaterequals", operand: "none" },
  { op: 0xb1, name: "instanceof", operand: "none" },
  { op: 0xb2, name: "istype", operand: "u30" },
  { op: 0xb3, name: "istypelate", operand: "none" },
  { op: 0xb4, name: "in", operand: "none" },
  { op: 0xc0, name: "increment_i", operand: "none" },
  { op: 0xc1, name: "decrement_i", operand: "none" },
  { op: 0xc2, name: "inclocal_i", operand: "u30" },
  { op: 0xc3, name: "declocal_i", operand: "u30" },
  { op: 0xc4, name: "negate_i", operand: "none" },
  { op: 0xc5, name: "add_i", operand: "none" },
  { op: 0xc6, name: "subtract_i", operand: "none" },
  { op: 0xc7, name: "multiply_i", operand: "none" },
  { op: 0xd0, name: "getlocal_0", operand: "none" },
  { op: 0xd1, name: "getlocal_1", operand: "none" },
  { op: 0xd2, name: "getlocal_2", operand: "none" },
  { op: 0xd3, name: "getlocal_3", operand: "none" },
  { op: 0xd4, name: "setlocal_0", operand: "none" },
  { op: 0xd5, name: "setlocal_1", operand: "none" },
  { op: 0xd6, name: "setlocal_2", operand: "none" },
  { op: 0xd7, name: "setlocal_3", operand: "none" },
  { op: 0xef, name: "debug", operand: "debug" },
  { op: 0xf0, name: "debugline", operand: "u30" },
  { op: 0xf1, name: "debugfile", operand: "u30" },
  { op: 0xf2, name: "bkptline", operand: "u30" },
  { op: 0xf3, name: "timestamp", operand: "none" },
];

export const OPCODES: Record<number, OpcodeInfo> = Object.fromEntries(TABLE.map((o) => [o.op, o]));

export function opcodeName(op: number): string {
  return OPCODES[op]?.name ?? `op_${op.toString(16)}`;
}
